{% set name = "plexapi" %}
{% set version = "4.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2c840668103a833c243654d9496c185c8f42cf7f94cf8cd95aad8e282d943ac6

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - requests
  run:
    - python
    - requests

test:
  imports:
    - plexapi

about:
  home: "https://github.com/pkkid/python-plexapi"
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "Python bindings for the Plex API."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
